---
title: "Jesica Formoso - CV"
editor: visual
---

## Overview

I am currently a Tenured Researcher at CIIPME-CONICET and serve as the Impact Measurement Coordinator and Instructor at MetaDocencia, where I advocate for Open Science across Latin America and the Caribbean. I am actively involved in communities of practice that support data science education, including co-organizing the Buenos Aires chapter of R-Ladies. I have over a decade of teaching experience as a faculty member at the University of Buenos Aires and more than five years of experience designing and teaching courses on statistics, R programming, and data science. Additionally, I contribute to open educational resources by developing tutorials, workshops, and course materials for teaching R programming, data science, and statistics in Spanish. I am also an Instructor and Trainer for The Carpentries and RStudio (now Posit).

[Download CV as PDF]()

## Selected education

**Ph.D., Ethical, Humanistic, and Social Medical Sciences (2017)**

-   Emphasis: Cognitive Development of Mathematical Skills in Children.
-   School of Medicine
-   University of Buenos Aires

**Specialization in Statistics for Health Sciences (2018)**

-   Institute of Calculus
-   School of Exact and Natural Sciences
-   University of Buenos Aires

**Specialization in Neuropsychology (2018)**

-   School of Psychology
-   University of Buenos Aires

**B.S., Psychology (2008)**

-   School of Psychology
-   University of Buenos Aires

## Selected research experience

**Tenured Researcher (2019-2022)** - Cognitive Studies lab at the Psychological Research Institute, School of Psychology, University of Buenos Aires (UBA) - National Scientific and Technical Research Council (CONICET)

**Tenured Researcher (2023-present)** - Interdisciplinary Center for Research in Mathematical and Experimental Psychology "Dr. Horacio J. A. Rimoldi" (CIIPME) - National Scientific and Technical Research Council (CONICET)

## Selected teaching experience

**Instructor and Trainer (2020 - present)** - Data Carpentry & The Carpentries - RStudio (Posit)

**Lead Instructor (2018 - 2024)** - R programming, Data analysis and visualization courses for graduate psychology and health students - UBA; Italian Hospital University Institute

**Assistant Teaching Professor (2013 - 2024)** - Statistics, BSc. in Psyhology, School of Psychology, UBA - Neurophysiology, BSc. in Psyhology, School of Psychology, UBA

## Selected community developments

**MetaDocencia - Impact Measurement Coordinator/Instructor (2022 - present)**

MetaDocencia is an organization committed to advancing Open Science practices across Latin America and the Caribbean. Its work focuses on capacity-building, adapting and creating educational resources in Spanish, and fostering a network of regional communities and stakeholders. Currently, it is part of the NASA TOPS initiative and serves as the contextualizer for NASA materials in Spanish.

**R-Ladies Buenos Aires - organizer/Instructor (2020 - present)**

R-Ladies is an international initiative dedicated to promoting diversity and inclusion within the R programming community. The Buenos Aires chapter organizes 3 to 6 events annually, featuring activities such as technical skill-building workshops, short presentations by members and guest speakers, as well as community-building and networking opportunities.

**LatinR - organizer committee (2023)**

Latin American Conference about the Use of R for Research + Development

## Selected talks and presentations

**Collective Creation of Open Science (2024).** Guest pannelist in the seminar [Promoting Open Science in and from the Global South](https://www.youtube.com/watch?v=LAn7cA5okSk) (first webinar from eLife’s Global South Committee for Open Science)

**Insights and Innovation in Virtual Training (2024).** Guest panellist in this webinar organized by Don't Use This Code and the NASA TOPS iniciative.

**Responsible Reseach & Decolonisation from a Latin American Perspective (2024).** Guest pannelist and organizer in the Summer School/Alumni Seminar: Decolonizing Global Health with a focus on Biomedical Sciences, Reseach and Education organized by Berlin Institute of Health, Charité, Quest Center and MetaDocencia.

**Mapping Open-Science Communities, Organizations & Events in Latin America (2023).** Lightning Talk within the Code for All Summit 2023.

**A Shiny-app for Mapping Open-Science Communities, Organizations & Events in Latin America (2023).** LatinR 2023: Latin American conference about the use of R in research and development.

**Communities of Practice in Latin America and their Influence on the Dissemination of Open-Science (2023)**. csv,conf,v7.

## Peer-reviewed publications

Most of my peer-reviewd publications can be found in [my google scholar profile](https://scholar.google.com/citations?hl=en&user=WiZFJHYAAAAJ&view_op=list_works&sortby=pubdate).

## Selected awards and scholarships

**KHIPU 2025**

-   *Latin American Meeting in Artificial Intelligence, Santiago, Chile* Selected to participate in this highly competitive event, recognized for academic excellence and contributions to diversity in AI research.

**Posit Opportunity Scholarship (2024)**

-   *Posit::conf(2024), Seattle, USA* Awarded funding to attend the Posit Conference 2024. Covered travel, accommodation, meals, and conference fees.

**External Fellowship for Young Researchers (2023)**

-   *National Scientific and Technical Research Council (CONICET)-* Awarded funding to conduct research under the supervision of Dr. Gracia Jiménez Fernández at the Department of Developmental and Educational Psychology, Faculty of Educational Sciences, University of Granada, Spain. This prestigious program supports the training of early-career researchers at leading international research institutions.

**DISC Unconference 2023**

-   *NumFOCUS, Amsterdam, Netherlands.* Invited and funded to attend the Diversity & Inclusion in Scientific Computing Unconference, a collaborative event focused on creating scalable solutions and resources to promote diversity and inclusion in open-source scientific computing.

**Postdoctoral Fellowship (2017)**

-   *National Scientific and Technical Research Council (CONICET)*

**IBRO Travel Grant (2014)**

-   *International Brain Research Organization.* Awarded funding to attend the **School of Neuroinformatics and Computational Neuroscience, 2014**.

**Doctoral Fellowship (2013)**

-   *Secretary of Science and Technology, University of Buenos Aires (UBACyT)*
