---
authors: [Jesica Formoso]
date: "2024-11-26"
title: Introduction to Quarto
---

The R-Ladies Buenos Aires workshop **Transform Your Data into Visual Stories with Quarto** presents an introduction to Quarto, an open-source publishing system designed to create dynamic and reproducible scientific and technical documents. It explores practical examples of its use in reproducible reports, covering topics such as integrating code and text, customizing output formats, and using parameters to create parameterized reports. This introductory workshop is aimed at individuals with a basic knowledge of R and little to no previous experience with Quarto.

**Learning Objectives:**

-   Get familiar with Quarto as a dynamic and reproducible publishing tool that expands the capabilities of RMarkdown.
-   Identify the possibilities it offers for creating scientific and technical documents, such as reports, presentations, and websites.
-   Learn how to combine explanatory text with executable code to generate reports that automatically update results.
-   Understand how to use parameters in Quarto to efficiently create different versions of the same document.

[Find recording and materials here.](https://jformoso.github.io/quarto-rladiesBA/)
